site_name: Service Catalogue 
site_url: https://service-catalogue.readthedocs.org
repo_url: https://github.com/OPSILab/Service-Catalogue
site_description: Service Catalogue
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: true
theme: readthedocs

nav:
  - 'Home': 'index.md' 
  - 'Introduction': 'introduction.md'
  - 'Installation Manual': 'install/index.md'
  - 'User Guide':
     - 'Service Catalogue Manager': 'usage/index.md'
     - 'How to describe a service': 'usage/service-model-howto.md'
  - 'API Documentation' : 'api/index.md'
  - 'Service Model Documentation': 'model/index.md'


