site_name: Service Catalogue 
site_url: https://service-catalogue.readthedocs.org
repo_url: https://github.com/OPSILab/Service-Catalogue
site_description: Service Catalogue
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: true
theme: readthedocs

pages:
  - 'Home': 'index.md' 
  - 'Architecture Overview': 'architecture/architecture.md'
  - 'Installation & Administration Manual':
      - 'Introduction': 'admin/index.md'
      - 'Installation overview': 'admin/installation.md'
      - 'Install with WARs packages': 'admin/install_war.md'
      - 'Install with Docker': 'admin/install_docker.md'
      - 'Sanity Checks': 'admin/sanitychecks.md'
      - 'Platform Management': 'admin/administration_gui.md'
      - 'Scraping Guide': 'admin/scraping.md'
  - 'User Guide':
      - 'Introduction': 'user/index.md'
      - 'How to use Idra': 'user/enduser.md'

