version: "3.8"
services:
  service-catalogue-manager:
    image: capesuite/service-catalogue-manager:latest
    build:
      context: .
      args:
        BASE_HREF: /service-catalogue-manager/
    ports:
      - "81:80"
    volumes:
      - ./src/assets/config.prod.json:/usr/share/nginx/html/assets/config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cape-network


networks:
 cape-network:
   name: service-catalogue-manager-network
   driver: bridge
   driver_opts:
     com.docker.network.driver.mtu: 1400
