/**
 * Service Catalog API
 * Service Catalog APIs used to manage CRUD for Service Model descriptions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Description2 } from './description2';

export interface HasChannel { 
    identifier: string;
    type: string;
    language?: Array<string>;
    description?: Array<Description2>;
    openingHours: string;
    hoursAvailable?: string;
    hasInput?:string[];
}

