/**
 * Service Catalog API
 * Service Catalog APIs used to manage CRUD for Service Model descriptions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HasContactPoint { 
    email?: string;
    faxNumber?: string;
    telephone?: string;
    identifier?: string;
    openingHours?: string;
    hoursAvailable?: string;
    url?:string;
}

