/**
 * Service Catalog API
 * Service Catalog APIs used to manage CRUD for Service Model descriptions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Description } from './description';
import { HasContactPoint } from './hasContactPoint';
import { HasInput } from './hasInput';
import { Produce } from './produce';
import { HasChannel } from './hasChannel';
import { HasCompetentAuthority } from './hasCompetentAuthority';
import { HasCost } from './hasCost';
import { IsDescribedAt } from './isDescribedAt';


export interface HasInfo { 
    identifier?: string;
    title: string;
    status: string;
    keyword: Array<string>;
    sector: Array<string>;
    thematicArea: Array<string>;
    type: Array<string>;
    language: Array<string>;
    description: Description;
    isDescribedAt: Array<IsDescribedAt>;
    hasCost: Array<HasCost>;
    processingTime: string;
    isGroupedBy: Array<string>;
    hasCompetentAuthority: HasCompetentAuthority;
    requires: Array<string>;
    spatial: string;
    hasInput: Array<HasInput>;
    produces: Array<Produce>;
    hasContactPoint: HasContactPoint;
    hasChannel: Array<HasChannel>;
    
}

