/**
 * Service Catalog API
 * Service Catalog APIs used to manage CRUD for Service Model descriptions.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShareWith } from './shareWith';
import { Storage } from './storage';
import { Obligation } from './obligation';
import { Description6 } from './description6';


export interface IsPersonalDataHandling { 
    purposeId: string;
    purposeName: string;
    legalBasis: string;
    purposeCategory: string;
    processingCategories: Array<string>;
    description: Array<Description6>;
    requiredDatasets: Array<string>;
    storage: Storage;
    recipients: Array<object>;
    shareWith: Array<ShareWith>;
    obligations: Array<Obligation>;
    policyRef: string;
    collectionMethod: string;
    collectionOperator: string;
    termination: string;
}

